### ISSUE TITLE
对Unicode 字符进行转义

### ISSUE THREAD

**Issue by chenshinshi** [frostime/sy-titled-link#1]
网页地址：
https://amabanatsuki.blogspot.com/2018/05/rusuban.html
获取标题：
![image](https://github.com/frostime/sy-titled-link/assets/125173405/4f038d55-a20f-4f34-a8d4-de8f264ba130)
原标题：
![image](https://github.com/frostime/sy-titled-link/assets/125173405/0715e5e1-69d4-4ab8-919f-9975b6613937)

**Comment by frostime** [comment]
Unicode字符的问题。

不过为啥我这里获取不到这个网址，你是给思源开了网络代理了吗。🙄
![image](https://github.com/frostime/sy-titled-link/assets/27268127/ad1afae6-7fda-4b2b-8c07-87ff407fd3fe)

**Comment by chenshinshi** [comment]
啊？？我是有挂智能分流的梯子

Frostime ***@***.***> 於 2023年11月4日 週六 下午3:37寫道：
