### ISSUE TITLE
【功能请求】使用系统代理获取链接标题

### ISSUE THREAD

**Issue by wanyunr** [frostime/sy-titled-link#2]
获取一些链接的标题的时候有如下报错，能否优先或可以设置使用系统代理获取链接
```
forward request failed: Get
"https://www.xxx.com: net/http: request
canceled while waiting for
connection (Client. Timeout
exceeded while awaiting headers)
````

**Comment by frostime** [comment]
思源的网络代理比较特别，不走系统代理，必须在软件内单独设置。

![image](https://github.com/frostime/sy-titled-link/assets/27268127/4c431048-4a5f-465e-8f89-cc4258664cb1)

**Comment by frostime** [comment]
这个只能通过思源的设置解决，插件没有能力管理到代理。详情见：https://github.com/siyuan-note/siyuan/issues/8989

先关了，有问题就继续在这里问。
