### ISSUE TITLE
[功能请求]是否可以尝试将获取到的标题设置为链接属性中的标题

### ISSUE THREAD

**Issue by emptylight370** [frostime/sy-titled-link#3]
如题，根据开发者工具观察得知，<a>标签中有一个属性`data-title`用于记录链接属性中的标题，在鼠标悬浮在<a>标签上时可以看到上下两行内容，分别是url和title。（此处的<a>标签实际上是html中的表述，思源中的展示形式为`<span data-type="a" data-href="http://" data-title="title">link</span>`）
经过测试，修改属性面板中的标题可以在`data-title`属性中同步显现，那么是否反过来也成立？是否可以通过修改`data-title`属性来操作属性中的标题值？
假定可行，又是否可以在插件中新增选项和函数来实现获取网站标题后替换属性中的标题，以及保留原有的替换链接文本功能？
在我的设想中，（如果无误的话）可以根据现有的函数，将替换`span.innerHtml`这一步调整为替换`span["data-title"]`从而达成调整标题属性的操作，但是新增功能意味着需要新建插件设置面板调整设置或者添加插件动作调用新函数。
不知道作者是如何考虑，获取网页标题设置属性中的标题属性是否可行，又是否有开发需要？如果需要提pr的话，我可以在假期期间尝试完成新的替换功能函数。

**Comment by frostime** [comment]
我可以理解为，你的需求是获取标题后，既设置锚文本又设置标题是吗？主要是我在实际使用的时候从来没有用过标题，也不知道这东西有啥用。

![image](https://github.com/frostime/sy-titled-link/assets/27268127/65fd0ede-c75a-495b-8011-32770f0ed7eb)

**Comment by emptylight370** [comment]
在描述过程中没有附图是我的问题，设置了标题之后的视觉效果如图所示。
![Clip_2023-12-31_11-46-52](https://github.com/frostime/sy-titled-link/assets/61617417/5e37cb83-cb19-4e1e-a258-07c4fc62d4a4)
标题属性是在鼠标悬浮时可以显示的附加文本，虽然平时没有存在感，但是这次刚好遇上一个需求用到这个属性，所以想到这个扩展插件，需求表述概括为添加一个新的按钮获取网页标题并设置标题属性。

**Comment by frostime** [comment]
那应该是可以的，不过是添加一个按钮好还是做一个全局设置选项好？

**Comment by emptylight370** [comment]
这我反倒是不太确定，看看哪种简单吧。
添加按钮需要的就是新的设置标题函数以及复制一次现有的按钮函数，好处是修改起来比较简单快速。
做设置面板需要新的设置标题函数，设置面板函数，保存读取配置文件函数，针对不同情况下的灵活调用，好处是可扩展性高。

或许设置参数时可以通过在调用函数时传参，然后根据参数if-else或者switch调用不同的设置参数语句。

**Comment by frostime** [comment]
先就增加一个按钮吧。做起来简单一点。

不过我这几天都比较忙，我自己来的话要过一段时间。你如果有空可以试着提交一个 pr。

**Comment by emptylight370** [comment]
我已经有添加按钮的思路了，遗憾的是，我正在考试周，也需要等一段时间
~先放着吧，不想挂科~
